name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  patcher-tests:
    name: Run Liquip.Patcher.Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add ilc Tool
        run: dotnet tool install ilc -g

      - name: Restore Dependencies
        run: dotnet restore ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj

      - name: Build Liquip.Patcher.Tests
        run: dotnet build ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Tests-Results
          path: ./Liquip.Patcher.Tests/TestResults/Liquip.Patcher.Tests.trx

  scanner-tests:
    name: Run Liquip.Scanner.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj

      - name: Build Liquip.Scanner.Tests
        run: dotnet build ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Scanner.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Scanner.Tests-Results
          path: ./Liquip.Scanner.Tests/TestResults/Liquip.Scanner.Tests.trx

  analyzer-tests:
    name: Run Liquip.Patcher.Analyzer.Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ./Liquip.Patcher.Analyzer/Liquip.Patcher.Analyzer.Test/Liquip.Patcher.Analyzer.Test.csproj

      - name: Build Liquip.Patcher.Analyzer.Test
        run: dotnet build  ./Liquip.Patcher.Analyzer/Liquip.Patcher.Analyzer.Test/Liquip.Patcher.Analyzer.Test.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test  ./Liquip.Patcher.Analyzer/Liquip.Patcher.Analyzer.Test/Liquip.Patcher.Analyzer.Test.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Analyzer.Test.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Analyzer.Test-Results
          path: ./Liquip.Patcher.Analyzer.Test/TestResults/Liquip.Patcher.Analyzer.Test.trx

