name: Package

on:
  push:
    branches:
      - main
  workflow_call:
jobs:
  pack-patcher:
    name: Pack Cosmos Patcher
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Pack Cosmos.Api
        run: dotnet build ./src/Cosmos.API/Cosmos.API.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Patcher.Build
        run: dotnet build ./src/Cosmos.Patcher.Build/Cosmos.Patcher.Build.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Patcher
        run: dotnet build ./src/Cosmos.Patcher/Cosmos.Patcher.csproj --configuration Release --artifacts-path ./out
        
      - name: Pack Cosmos.Common.Build
        run: dotnet build ./src/Cosmos.Common.Build/Cosmos.Common.Build.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Ilc.Build
        run: dotnet build ./src/Cosmos.Ilc.Build/Cosmos.Ilc.Build.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Asm.Build
        run: dotnet build ./src/Cosmos.Asm.Build/Cosmos.Asm.Build.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Patcher.Analyzer.Package
        run: dotnet build ./src/Cosmos.Patcher.Analyzer.Package/Cosmos.Patcher.Analyzer.Package.csproj  --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Kernel.Native.x86
        run: dotnet build ./src/Cosmos.Kernel.Native.x86/Cosmos.Kernel.Native.x86.csproj --configuration Release --artifacts-path ./out

      - name: Pack Cosmos.Sdk
        run: dotnet build ./src/Cosmos.Sdk/Cosmos.Sdk.csproj  --configuration Release --artifacts-path ./out

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: Cosmos.Patcher.Packages
          path: ./out/package/release


